---
- name: copy identity files
  copy:
    src: ../files/identity
    dest: /opt

- name: deploy/restart identity apps 
  community.docker.docker_compose_v2:
    project_src: /opt/identity
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output
