---
- name: copy enakes files
  copy:
    src: ../files/enakes
    dest: /opt

- name: deploy/restart enakes apps 
  community.docker.docker_compose_v2:
    project_src: /opt/enakes
    files: 
      - "docker-compose.yaml"
      - "docker-compose-s3.yaml"
    state: present
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output
