name: kuala-microservices

x-logging: &default-logging
  driver: loki:latest
  options:
    loki-url: "https://${GRAFANA_USER}:${GRAFANA_TOKEN}@${GRAFANA_HOST}/loki/api/v1/push"
    loki-batch-size: 400


services:
    account-service:
        build:
            context: ./
            dockerfile: services/account-service/Dockerfile
        container_name: account-service
        ports:
            - "9001:8001"
        env_file:
            - ./services/account-service/.env
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8001"]
            interval: 15s
            timeout: 5s
            retries: 5
            start_period: 30s
        restart: unless-stopped
        logging: *default-logging

    invoice-service:
        build:
            context: ./
            dockerfile: services/invoice-service/Dockerfile
        container_name: invoice-service
        ports:
            - "9002:8002"
        env_file:
            - ./services/invoice-service/.env
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8002"]
            interval: 15s
            timeout: 5s
            retries: 5
            start_period: 30s
        restart: unless-stopped
        logging: *default-logging

    subscription-service:
        build:
            context: ./
            dockerfile: services/subscription-service/Dockerfile
        container_name: subscription-service
        ports:
            - "9003:8003"
        env_file:
            - ./services/subscription-service/.env
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8003"]
            interval: 15s
            timeout: 5s
            retries: 5
            start_period: 30s
        restart: unless-stopped
        logging: *default-logging
