name: kuala-microservices

services:
    account-service:
        build:
            context: ./
            dockerfile: account-service/Dockerfile
        container_name: account-service
        ports:
            - "9001:8001"
        env_file:
            - ./account-service/.env
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8001"]
            interval: 15s
            timeout: 5s
            retries: 5
            start_period: 30s
        restart: unless-stopped
        networks:
          - rabbitmq

    invoice-service:
        build:
            context: ./
            dockerfile: invoice-service/Dockerfile
        container_name: invoice-service
        ports:
            - "9002:8002"
        env_file:
            - ./invoice-service/.env
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8002"]
            interval: 15s
            timeout: 5s
            retries: 5
            start_period: 30s
        restart: unless-stopped
        networks:
          - rabbitmq

    subscription-service:
        build:
            context: ./
            dockerfile: subscription-service/Dockerfile
        container_name: subscription-service
        ports:
            - "9003:8003"
        env_file:
            - ./subscription-service/.env
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8003"]
            interval: 15s
            timeout: 5s
            retries: 5
            start_period: 30s
        restart: unless-stopped
        networks:
          - rabbitmq

networks:
  rabbitmq:
    name: rabbitmq
    external: true  
