---
- name: copy eimunisasi files
  copy:
    src: ../files/eimunisasi
    dest: /opt

- name: deploy/restart eimunisasi apps 
  community.docker.docker_compose_v2:
    project_src: /opt/eimunisasi
    files: 
      - "docker-compose.yaml"
      - "docker-compose-s3.yaml"
    state: present
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output
