---
- name: "Create directory"
  file:
    path: /opt/eimunisasi
    state: directory

- name: deploy apps
  include_tasks: apps.yaml

- name: Run seeds script
  ansible.builtin.shell: docker exec eimunisasi-db /bin/sh -c 'sh /run_seeds.sh'

