---
- name: Install python pip
  apt:
    pkg: 
    - python3-pip
    - python-is-python3
    - unzip

- name: Install pip docker
  pip:
    name: docker

- name: Install pip docker-compose
  pip:
    name: docker-compose  