---
- name: copy rabbitmq files
  copy:
    src: ../files/
    dest: /opt/rabbitmq/

- name: deploy/restart rabbitmq apps 
  community.docker.docker_compose_v2:
    project_src: /opt/rabbitmq
    files: 
      - "docker-compose.yml"
    state: present
    environment:
      DOCKER_USERNAME: "{{ lookup('env', 'DOCKER_USERNAME') }}"
      DOCKER_PASSWORD: "{{ lookup('env', 'DOCKER_PASSWORD') }}"
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output
