---
- name: copy supabase files
  copy:
    src: ../files/supabase
    dest: /opt

- name: deploy/restart supabase apps 
  community.docker.docker_compose_v2:
    project_src: /opt/supabase
    files: 
      - "docker-compose.yaml"
      - "docker-compose-s3.yaml"
    state: present
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output
