---
- name: Allow SSH 
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow 80 
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow 443 
  ufw:
    rule: allow
    port: 443
    proto: tcp