-- migrate:up


--
-- Name: handle_new_user(); Type: FUNCTION; Schema: public;
--

CREATE FUNCTION public.handle_new_user() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.profiles WHERE user_id = new.id) THEN
    INSERT INTO public.profiles (user_id, avatar_url, full_name)
    VALUES (new.id, new.raw_user_meta_data->>'avatar_url',new.raw_user_meta_data->>'full_name');
  END IF;
  RETURN new;
END;$$;

--
-- Name: blog_tags; Type: TABLE; Schema: public;
--

CREATE TABLE public.blog_tags (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying NOT NULL
);


--
-- Name: blogs; Type: TABLE; Schema: public;
--

CREATE TABLE public.blogs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    tag_id uuid,
    title character varying NOT NULL,
    body text NOT NULL,
    author character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    update_at timestamp with time zone
);


--
-- Name: calendars; Type: TABLE; Schema: public;
--

CREATE TABLE public.calendars (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid DEFAULT auth.uid(),
    activity character varying NOT NULL,
    do_at timestamp with time zone NOT NULL,
    read_only boolean DEFAULT false
);


--
-- Name: clinic_schedules; Type: TABLE; Schema: public; 
--

CREATE TABLE public.clinic_schedules (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    clinic_id uuid NOT NULL,
    day_id bigint,
    start_time time without time zone,
    end_time time without time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone
);



--
-- Name: clinics; Type: TABLE; Schema: public; 
--

CREATE TABLE public.clinics (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying NOT NULL,
    address text,
    motto character varying,
    phone_number character varying,
    photos text[],
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: days; Type: TABLE; Schema: public; 
--

CREATE TABLE public.days (
    id bigint NOT NULL,
    name character varying NOT NULL
);

--
-- Name: days_id_seq; Type: SEQUENCE; Schema: public; 
--

ALTER TABLE public.days ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.days_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hospitals; Type: TABLE; Schema: public; 
--

CREATE TABLE public.hospitals (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying NOT NULL,
    address text NOT NULL,
    telephone character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone
);

--
-- Name: notifications; Type: TABLE; Schema: public; 
--

CREATE TABLE public.notifications (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid DEFAULT auth.uid(),
    title character varying NOT NULL,
    body character varying NOT NULL,
    is_read boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone
);

--
-- Name: practice_schedules; Type: TABLE; Schema: public; 
--

CREATE TABLE public.practice_schedules (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    day_id bigint NOT NULL,
    start_time time without time zone,
    end_time time without time zone,
    created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
    updated_at timestamp with time zone
);

--
-- Name: profiles; Type: TABLE; Schema: public; 
--

CREATE TABLE public.profiles (
    avatar_url text,
    place_of_birth character varying,
    date_of_birth date,
    no_induk_kependudukan character varying,
    no_kartu_keluarga character varying,
    full_name character varying,
    profession character varying,
    phone_number character varying,
    clinic_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone,
    user_id uuid DEFAULT auth.uid() NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL
);

--
-- Name: blog_tags blog_tags_pkey; Type: CONSTRAINT; Schema: public; 
--

ALTER TABLE ONLY public.blog_tags
    ADD CONSTRAINT blog_tags_pkey PRIMARY KEY (id);


--
-- Name: blogs blogs_pkey; Type: CONSTRAINT; Schema: public; 
--

ALTER TABLE ONLY public.blogs
    ADD CONSTRAINT blogs_pkey PRIMARY KEY (id);


--
-- Name: calendars calendars_pkey; Type: CONSTRAINT; Schema: public; 
--

ALTER TABLE ONLY public.calendars
    ADD CONSTRAINT calendars_pkey PRIMARY KEY (id);


--
-- Name: clinic_schedules clinic_schedules_pkey; Type: CONSTRAINT; Schema: public; 
--

ALTER TABLE ONLY public.clinic_schedules
    ADD CONSTRAINT clinic_schedules_pkey PRIMARY KEY (id);


--
-- Name: clinics clinics_pkey; Type: CONSTRAINT; Schema: public; 
--

ALTER TABLE ONLY public.clinics
    ADD CONSTRAINT clinics_pkey PRIMARY KEY (id);


--
-- Name: days days_pkey; Type: CONSTRAINT; Schema: public; 
--

ALTER TABLE ONLY public.days
    ADD CONSTRAINT days_pkey PRIMARY KEY (id);


--
-- Name: hospitals hospitals_pkey; Type: CONSTRAINT; Schema: public; 
--

ALTER TABLE ONLY public.hospitals
    ADD CONSTRAINT hospitals_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; 
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: practice_schedules practice_schedules_pkey; Type: CONSTRAINT; Schema: public; 
--

ALTER TABLE ONLY public.practice_schedules
    ADD CONSTRAINT practice_schedules_pkey PRIMARY KEY (id);


--
-- Name: profiles profiles_pkey; Type: CONSTRAINT; Schema: public; 
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (user_id, id);


--
-- Name: profiles profiles_user_id_key; Type: CONSTRAINT; Schema: public; 
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_user_id_key UNIQUE (user_id);


--
-- Name: blogs blogs_tag_id_fkey; Type: FK CONSTRAINT; Schema: public; 
--

ALTER TABLE ONLY public.blogs
    ADD CONSTRAINT blogs_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.blog_tags(id) ON DELETE SET NULL;


--
-- Name: calendars calendars_user_id_fkey; Type: FK CONSTRAINT; Schema: public; 
--

ALTER TABLE ONLY public.calendars
    ADD CONSTRAINT calendars_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: clinic_schedules clinic_schedules_clinic_id_fkey; Type: FK CONSTRAINT; Schema: public; 
--

ALTER TABLE ONLY public.clinic_schedules
    ADD CONSTRAINT clinic_schedules_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: clinic_schedules clinic_schedules_day_id_fkey; Type: FK CONSTRAINT; Schema: public; 
--

ALTER TABLE ONLY public.clinic_schedules
    ADD CONSTRAINT clinic_schedules_day_id_fkey FOREIGN KEY (day_id) REFERENCES public.days(id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: notifications notifications_user_id_fkey; Type: FK CONSTRAINT; Schema: public; 
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: practice_schedules practice_schedules_day_id_fkey; Type: FK CONSTRAINT; Schema: public; 
--

ALTER TABLE ONLY public.practice_schedules
    ADD CONSTRAINT practice_schedules_day_id_fkey FOREIGN KEY (day_id) REFERENCES public.days(id);


--
-- Name: practice_schedules practice_schedules_user_id_fkey; Type: FK CONSTRAINT; Schema: public; 
--

ALTER TABLE ONLY public.practice_schedules
    ADD CONSTRAINT practice_schedules_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(user_id) ON DELETE SET NULL;


--
-- Name: profiles profiles_clinic_id_fkey; Type: FK CONSTRAINT; Schema: public; 
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: profiles profiles_user_id_fkey; Type: FK CONSTRAINT; Schema: public; 
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);


--
-- Name: calendars Enable delete for users based on user_id; Type: POLICY; Schema: public; 
--

CREATE POLICY "Enable delete for users based on user_id" ON public.calendars FOR DELETE TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: calendars Enable insert for users based on user_id; Type: POLICY; Schema: public; 
--

CREATE POLICY "Enable insert for users based on user_id" ON public.calendars FOR INSERT TO authenticated WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: calendars Enable read access for authenticated same user_id; Type: POLICY; Schema: public; 
--

CREATE POLICY "Enable read access for authenticated same user_id" ON public.calendars FOR SELECT TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: calendars Enable update for users based on user_id; Type: POLICY; Schema: public; 
--

CREATE POLICY "Enable update for users based on user_id" ON public.calendars FOR UPDATE TO authenticated USING ((( SELECT auth.uid() AS uid) = user_id)) WITH CHECK ((( SELECT auth.uid() AS uid) = user_id));


--
-- Name: blog_tags; Type: ROW SECURITY; Schema: public; 
--

ALTER TABLE public.blog_tags ENABLE ROW LEVEL SECURITY;

--
-- Name: blogs; Type: ROW SECURITY; Schema: public; 
--

ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;

--
-- Name: calendars; Type: ROW SECURITY; Schema: public; 
--

ALTER TABLE public.calendars ENABLE ROW LEVEL SECURITY;

--
-- Name: days; Type: ROW SECURITY; Schema: public; 
--

ALTER TABLE public.days ENABLE ROW LEVEL SECURITY;

--
-- Name: hospitals; Type: ROW SECURITY; Schema: public; 
--

ALTER TABLE public.hospitals ENABLE ROW LEVEL SECURITY;

--
-- Name: notifications; Type: ROW SECURITY; Schema: public; 
--

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

--
-- Name: clinic_schedules; Type: ROW SECURITY; Schema: public; 
--

ALTER TABLE public.clinic_schedules ENABLE ROW LEVEL SECURITY;

--
-- Name: clinics; Type: ROW SECURITY; Schema: public; 
--

ALTER TABLE public.clinics ENABLE ROW LEVEL SECURITY;

--
-- Name: practice_schedules; Type: ROW SECURITY; Schema: public; 
--

ALTER TABLE public.practice_schedules ENABLE ROW LEVEL SECURITY;

--
-- Name: profiles; Type: ROW SECURITY; Schema: public; 
--

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

--
-- Name: days select_days_policy; Type: POLICY; Schema: public; 
--

CREATE POLICY select_days_policy ON public.days FOR SELECT TO authenticated USING (true);

--
-- Name: blog_tags all_rls_blog_tags; Type: POLICY; Schema: public; 
--

CREATE POLICY all_rls_blog_tags
ON public.blog_tags
to authenticated, service_role
USING (true);

--
-- Name: blogs all_rls_blogs; Type: POLICY; Schema: public; 
--

CREATE POLICY all_rls_blogs
ON public.blogs
to authenticated, service_role
USING (true);

--
-- Name: clinic_schedules all_rls_clinic_schedules; Type: POLICY; Schema: public; 
--

CREATE POLICY all_rls_clinic_schedules
ON public.clinic_schedules
to authenticated, service_role
USING (true);

--
-- Name: clinics all_rls_clinics; Type: POLICY; Schema: public; 
--

CREATE POLICY all_rls_clinics
ON public.clinics
to authenticated, service_role
USING (true);

--
-- Name: hospitals all_rls_hospitals; Type: POLICY; Schema: public; 
--

CREATE POLICY all_rls_hospitals
ON public.hospitals
to authenticated, service_role
USING (true);

--
-- Name: notifications all_rls_notifications; Type: POLICY; Schema: public; 
--

CREATE POLICY all_rls_notifications
ON public.notifications
to authenticated, service_role
USING (true);

--
-- Name: practice_schedules all_rls_practice_schedules; Type: POLICY; Schema: public; 
--

CREATE POLICY all_rls_practice_schedules
ON public.practice_schedules
to authenticated, service_role
USING (true);

--
-- Name: profiles all_rls_profiles; Type: POLICY; Schema: public; 
--

CREATE POLICY all_rls_profiles
ON public.profiles
to authenticated, service_role
USING (true);


-- migrate:down
DROP TABLE IF EXISTS public.blog_tags CASCADE;
DROP TABLE IF EXISTS public.blogs CASCADE;
DROP TABLE IF EXISTS public.calendars CASCADE;
DROP TABLE IF EXISTS public.clinic_schedules CASCADE;
DROP TABLE IF EXISTS public.clinics CASCADE;
DROP TABLE IF EXISTS public.days CASCADE;
DROP SEQUENCE IF EXISTS public.days_id_seq CASCADE;
DROP TABLE IF EXISTS public.hospitals CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.practice_schedules CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
DROP POLICY IF EXISTS "Enable delete for users based on user_id" ON public.calendars CASCADE;
DROP POLICY IF EXISTS "Enable insert for users based on user_id" ON public.calendars CASCADE;
DROP POLICY IF EXISTS "Enable read access for authenticated same user_id" ON public.calendars CASCADE;
DROP POLICY IF EXISTS "Enable update for users based on user_id" ON public.calendars CASCADE;
DROP POLICY IF EXISTS select_days_policy ON public.days CASCADE;
DROP POLICY IF EXISTS all_rls_blog_tags ON public.blog_tags CASCADE;
DROP POLICY IF EXISTS all_rls_blogs ON public.blogs CASCADE;
DROP POLICY IF EXISTS all_rls_clinic_schedules ON public.clinic_schedules CASCADE;
DROP POLICY IF EXISTS all_rls_clinics ON public.clinics CASCADE;
DROP POLICY IF EXISTS all_rls_hospitals ON public.hospitals CASCADE;
DROP POLICY IF EXISTS all_rls_notifications ON public.notifications CASCADE;
DROP POLICY IF EXISTS all_rls_practice_schedules ON public.practice_schedules CASCADE;
DROP POLICY IF EXISTS all_rls_profiles ON public.profiles CASCADE;
ALTER TABLE public.blog_tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.blogs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.calendars DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.clinic_schedules DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.clinics DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.days DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.hospitals DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.practice_schedules DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY; 