---
- name: copy reverse-proxy configuration
  copy:
    src: ../files/reverse-proxy
    dest: /opt

- name: deploy/restart reverse-proxy 
  community.docker.docker_compose_v2:
    project_src: /opt/reverse-proxy
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output
