---
- name: Copy kuala-microservices files
  copy:
    src: ../files/
    dest: "{{ kuala_microservices_dest_dir }}/"

- name: Copy microservice directories
  copy:
    src: "{{ kuala_api_src_dir }}/{{ item }}/"
    dest: "{{ kuala_microservices_dest_dir }}/{{ item }}"
  loop: "{{ microservices_list }}"

- name: Copy deno configuration files for each service
  copy:
    src: "{{ kuala_api_src_dir }}/{{ item.1 }}"
    dest: "{{ kuala_microservices_dest_dir }}/{{ item.0 }}/{{ item.1 }}"
  loop: "{{ microservices_list | product(['deno.json', 'deno.lock']) | list }}"
  loop_control:
    label: "{{ item.0 }} -> {{ item.1 }}"

- name: Copy shared library for each service
  copy:
    src: "{{ kuala_api_src_dir }}/supabase/functions/_shared/"
    dest: "{{ kuala_microservices_dest_dir }}/supabase/functions/_shared/"

- name: Deploy kuala-microservices apps 
  community.docker.docker_compose_v2:
    project_src: "{{ kuala_microservices_dest_dir }}"
    files: 
      - "services/docker-compose.yml"
    state: present
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output
