x-logging:
  &default-logging
  driver: loki:latest
  options:
    loki-url: "https://${GRAFANA_USER}:${GRAFANA_TOKEN}@${GRAFANA_HOST}/loki/api/v1/push"
    loki-batch-size: 400

services:
  reverse-proxy:
    container_name: reverse-proxy
    hostname: reverse-proxy
    image: nginx:stable
    restart: always
    ports:
      - 10080
      - 10443
    networks:
      - backend
      - supabase_default
      - identity_default
      - eimunisasi_default
    volumes:
      - ./config:/etc/nginx/config
      - ./conf.d:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /opt/letsencrypt:/etc/letsencrypt:ro  
      - ./static:/www/static  
    logging: *default-logging

networks:
  backend:
    name: backend
    external: true
  supabase_default:
    name: supabase_default
    external: true 
  identity_default:
    name: identity_default
    external: true     
  eimunisasi_default:
    name: eimunisasi_default
    external: true    
   