services:
  reverse-proxy:
    container_name: reverse-proxy
    hostname: reverse-proxy
    image: nginx:stable
    restart: always
    networks:
      - backend
      - supabase_default
    volumes:
      - ./config:/etc/nginx/config
      - ./conf.d:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /opt/letsencrypt:/etc/letsencrypt:ro  
      - ./static:/www/static  
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"    

networks:
  backend:
    name: backend
    external: true
  supabase_default:
    name: supabase_default
    external: true 
   