version: '3'

services:
  loadbalancer:
    container_name: loadbalancer
    hostname: loadbalancer
    image: nginx:stable
    restart: always
    depends_on:
      certbot:
        condition: service_started
    networks:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s         
    volumes:
      - ./config:/etc/nginx/config
      - ./conf.d:/etc/nginx/conf.d
      - ./tcpconf.d:/etc/nginx/tcpconf.d
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf 
      - ./certbot:/var/www/certbot
      - /opt/letsencrypt:/etc/letsencrypt:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  certbot:
    image: certbot/certbot:v2.7.0
    container_name: certbot
    restart: unless-stopped
    volumes:
      - /opt/letsencrypt:/etc/letsencrypt
      - /opt/letsencrypt/log:/var/log/letsencrypt
      - ./certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot certificates; sleep 12h & wait $${!}; done;'"

networks:
  frontend:
    name: frontend
  backend:
    name: backend