---
- name: Delete static folder
  ansible.builtin.file:
    path: /opt/static
    state: absent

- name: copy static folder
  copy:
    src: ../files/static
    dest: /opt

- name: deploy/restart static webserver
  community.docker.docker_compose_v2:
    project_src: /opt/static
    state: present
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output
