name: Run eimunisasi playbook
on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch Name'
        default: 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Get info
      run: |
          ls -al
          echo "Branch Name: $BRANCH_NAME"
      env:
        BRANCH_NAME: ${{ inputs.branch_name }}
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: playbook/eimunisasi.yaml
        directory: ./ansible
        key: ${{secrets.SSH_PRIVATE_KEY}}
        requirements: ./requirements.yml
        options: |
          -i inventory/base.ini
          --verbose        
      env:
        ANSIBLE_HOST_KEY_CHECKING: false
  
