name: Run killbill playbook
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ansible/roles/killbill/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo with submodules
        uses: actions/checkout@v4

      - name: Run killbill playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook/killbill.yaml
          directory: ./ansible
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}
          requirements: ./requirements.yml
          options: |
            -i inventory/base.ini
            --verbose        
            --tags=killbill
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
