name: Run static playbook
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: playbook/static.yaml
        directory: ./ansible
        key: ${{secrets.SSH_PRIVATE_KEY}}
        requirements: ./requirements.yml
        options: |
          -i inventory/base.ini
          --verbose        
          --tags=static
      env:
        ANSIBLE_HOST_KEY_CHECKING: false
  
