name: rabbitmq

x-logging: &default-logging
  driver: loki:latest
  options:
    loki-url: "https://${GRAFANA_USER}:${GRAFANA_TOKEN}@${GRAFANA_HOST}/loki/api/v1/push"
    loki-batch-size: 400

services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        hostname: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        env_file:
            - .env
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        logging: *default-logging

volumes:
    rabbitmq_data:
